apiVersion: v1
data:
  ALLOWED_CLIENT_HOSTS: "localhost,127.0.0.1,35.226.6.22,10.20.128.45"
  DEBUG: "False"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"ALLOWED_CLIENT_HOSTS":"localhost,127.0.0.1,35.226.6.22","DEBUG":"False"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"saleor-api-config","namespace":"default"}}
  creationTimestamp: "2024-09-14T14:25:09Z"
  name: saleor-api-config
  namespace: default
  resourceVersion: "8487801"
  uid: 8cc97962-3676-4c00-bae2-e9b1656789f3
