apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: saleor-api
  template:
    metadata:
      labels:
        app: saleor-api
    spec:
      containers:
        - name: saleor-api
          image: Aayush0133/saleor-api:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: saleor-api-env
